# Generated by Django 4.0.2 on 2022-11-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cream',
            name='created',
        ),
        migrations.RemoveField(
            model_name='cream',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='cream',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='cream',
            name='types',
        ),
        migrations.RemoveField(
            model_name='cream',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='type',
            name='created',
        ),
        migrations.RemoveField(
            model_name='type',
            name='updated',
        ),
        migrations.AddField(
            model_name='cream',
            name='raiting',
            field=models.PositiveBigIntegerField(choices=[(1, 'Muy mala'), (2, 'Mala'), (3, 'Buena'), (4, 'Muy buena'), (5, 'Excelente')], default=1),
        ),
        migrations.AlterField(
            model_name='cream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop'),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
