# Generated by Django 4.0.2 on 2022-11-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_remove_cream_marca_remove_cream_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='raiting',
            field=models.PositiveBigIntegerField(choices=[(1, 'Muy mala'), (2, 'Mala'), (3, 'Buena'), (4, 'Muy Buena'), (5, 'Exelente')], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='cream',
            name='raiting',
            field=models.PositiveBigIntegerField(default=1, max_length=5, verbose_name=[(1, 'Muy mala'), (2, 'Mala'), (3, 'Buena'), (4, 'Muy Buena'), (5, 'Exelente')]),
        ),
    ]
