# Generated by Django 4.0.2 on 2022-11-15 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_remove_cream_created_remove_cream_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='cream',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.cream', verbose_name='Crema'),
        ),
    ]
